### ISSUE TITLE
cannot compile C functions Windows (Unable to find vcvarsall.bat)

### ISSUE THREAD

**Issue by abhinav27s** [MTG/sms-tools#100]
As per following the installation on giving the following command on windows to compile C functions,
$ python compileModule.py build_ext --inplace

I am getting below error :
building 'utilFunctions_C' extension
error: Unable to find vcvarsall.bat

It seems to be some kind of c/c++ dependency needed to be installed.
Can anyone help to resolve the above error

**Comment by luizmendes** [comment]
Hi there.

I've recently tried to get sms-tools working on Windows machine, and the suggestion (1) from here: https://github.com/MTG/sms-tools/wiki/sms-tools-in-Windows  

solved this issue for me.

Hope it helps!

**Comment by fergarciadlc** [comment]
Thanks for the reference @luizmendes . It solved the issue for me as well.
