### ISSUE TITLE
SMS Self Registration

### ISSUE THREAD

**Issue by rajeshmittal1884** [MTG/sms-tools#101]
Hi guys, I'm Rajesh Mittal.. I'm developing an SMS gateway and have gone through various messaging sites like - [mobishastra.in](url), [kaamilsms.com](url), [msg91.com](url), smscountry.com and have seen them with sms registration part. They have json query added to it to pull data but I do not get how to post query and fetch it back. This has stopped my project, do not know to move ahead. Please collaborate on my project.

**Comment by vaibhavvimal** [comment]
> Hi guys, I'm Rajesh Mittal.. I'm developing an SMS gateway and have gone through various messaging sites like - [mobishastra.in](url), [kaamilsms.com](url), [msg91.com](url), smscountry.com and have seen them with sms registration part. They have json query added to it to pull data but I do not get how to post query and fetch it back. This has stopped my project, do not know to move ahead. Please collaborate on my project.

Hi Rajesh, gotta be kidding use the following quote for post:


<form action="https://zzzzzzzzz.com/abc.aspx" method="post">
--
  | <div class="form-group">
  | <h5>login</h5>
  | <input type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" name="txtEMail" placeholder="Profile ID">
  | </div>
  | <div class="form-group">
  | <input type="password" class="form-control" id="exampleInputPassword1" name="txtPassword" placeholder="Password">
  | </div>
  | <button type="submit" class="btn submit_button btn-primary">Submit</button>
  | </form>
