### ISSUE TITLE
Unable to use models_GUI.py and transformations_GUI.py (ATTRIBUTE Error)

### ISSUE THREAD

**Issue by Ajiket** [MTG/sms-tools#106]
Respected Sir,
I have downloaded SMS-tools Zip folder. 

However, I am unable to use some of the modules such as sine/Harmonic/SPR/SPS/HPR/HPS of the models_GUI.py file and transformations_GUI.py file. I am getting attribute error. 

I have downloaded the latest version of sms-tools, but I am getting a attribute error both in windows and ubuntu which I using on a Virtual machine. I have attached the screenshots for you reference.

Kindly suggest appropriate solution for the issue.

Thanking You,
Ajiket 

![models_interface](https://user-images.githubusercontent.com/68552171/91145399-04b9e100-e6d3-11ea-804c-4b42f5661eeb.JPG)
![transformations_GUI](https://user-images.githubusercontent.com/68552171/91145406-0683a480-e6d3-11ea-91a0-312b3fea4f58.JPG)
###

**Comment by BrendanJamesLynskey** [comment]
I see a similar same thing. My version of Python is 3.7.6 (Anaconda).

Best regards.

![Screenshot from 2020-09-03 21-25-49](https://user-images.githubusercontent.com/27049659/92163797-2b42ef00-ee2c-11ea-9731-8d2ace282b3b.png)

**Comment by BrendanJamesLynskey** [comment]
I fixed this by following the instructions in README.md, found in the top directory. I needed to compile the C modules.

Works fine now - really interesting tools!

**Comment by Ajiket** [comment]
Dear Brendan,
Thank You very much for your comment. I am now able to use all the tools.
