### ISSUE TITLE
HPS Morph transformation error

### ISSUE THREAD

**Issue by freemanfromgodotengine** [MTG/sms-tools#121]
I use Ubuntu 20.04.2 LTS.

When applying HPS Morph transformation to analyzed default sounds (violin-B3.wav and soprano-E4.wav) I see:

> Exception in Tkinter callback
> Traceback (most recent call last):
>   File "/home/linuxuser/anaconda3/lib/python3.8/tkinter/__init__.py", line 1883, in __call__
>     return self.func(*args)
>   File "/home/linuxuser/sms-tools/software/transformations_interface/hpsMorph_GUI_frame.py", line 376, in transformation_synthesis
>     hM.transformation_synthesis(inputFile1, fs, hfreq1, hmag1, stocEnv1, inputFile2, hfreq2, hmag2, stocEnv2, hfreqIntp, hmagIntp, stocIntp)
>   File "/home/linuxuser/sms-tools/software/transformations_interface/hpsMorph_function.py", line 125, in transformation_synthesis
>     yhfreq, yhmag, ystocEnv = HPST.hpsMorph(hfreq1, hmag1, stocEnv1, hfreq2, hmag2, stocEnv2, hfreqIntp, hmagIntp, stocIntp)
>   File "/home/linuxuser/sms-tools/software/transformations_interface/../transformations/hpsTransformations.py", line 72, in hpsMorph
>     harmonics = np.intersect1d(np.array(np.nonzero(hfreq1[l,:]), dtype=np.int)[0], np.array(np.nonzero(hfreq2[int(round((L2*l)/float(L1-1))),:]), dtype=np.int)[0])
> IndexError: index 406 is out of bounds for axis 0 with size 406

Any idea how to fix it?
Is it related to #109 issue?

**Comment by brizolara** [comment]
It looks like it's the same error... at lines 74, 76, 78 and 80 we have to substitute `L2` for `(L2-1)`.

Explanation: This way, at the last iteration of the `for` loop, `l` equals `L-1`, that divided by `L-1` equals `1`... and we are left with index `L2-1`, the last of the `hfreq2` \ `hmag2` \ `stocEnv2` array...
