### ISSUE TITLE
Ubuntu installation instructions seem to not be working

### ISSUE THREAD

**Issue by royk** [MTG/sms-tools#130]
This is using Ubuntu via WSL on windows. Following the installation instruction in the README, I get the following output:
`
sudo apt-get install python-dev ipython python-numpy python-matplotlib python-scipy cython

Reading package lists... Done

Building dependency tree

Reading state information... Done

Note, selecting 'python-dev-is-python2' instead of 'python-dev'
Package python-matplotlib is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

Package python-scipy is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

Package ipython is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'ipython' has no installation candidate

E: Package 'python-matplotlib' has no installation candidate

E: Package 'python-scipy' has no installation candidate

```

**Comment by ffagerholm** [comment]
I faced similar problems when I tried to test the tools today.

How I got it running in Ubuntu was first installing `python3-dev` using 
`$ sudo apt-get install python3-dev`  (seems to be required to be able to compile the C code)

Then you can install the python packages using pip:
`$ pip3 install ipython numpy matplotlib scipy cython`

I recommend installing the python packages inside an [virtual environment](https://docs.python.org/3/library/venv.html).

Then compile the C code in `software/models/utilFunctions_C`
`$ python compileModule.py build_ext --inplace`

For the plotting to work I also had to install `tkinter`
`$ sudo apt install python3.8-tk`

I noticed some bugs related to plotting, for example when running the STFS analysis in models_GUI. `TypeError` from matplotlib. I was able to get those working for the default examples by changing the array dimensions, but not sure if it works in general.

**Comment by garraww** [comment]
It seems that the SMS-tools have some compatibility issues with a lot of python package. 

I suggested you to use Pycharm so you can choose yourself an old version of these modules. 
For example, I am on python 3.7 and I use the matplotlib version (3.5.0), numpy version (1.21.0), and scipy version (1.7.3). 

With the python console of PyCharm, you can see which of those have not been recognised  and try to downgrade it
