### ISSUE TITLE
Python 3.9 changes for compatibility and to remove exceptions.

### ISSUE THREAD

**Issue by dwsdolce** [MTG/sms-tools#133]
It appears that sms-tools does not work with SciPy 1.9 since it has removed hanning. It also appears that all of the window function have been moved from scipy.signal to scipy.signal.windows.
This shows up in the uses of from scipy.signal import hanning in spsModel.py and stochasticModel.py.

**Comment by dwsdolce** [comment]
I have made changes that make sms-tools work on Python 3.9. Please see https://github.com/dwsdolce/sms-tools/commit/bfe4a4f891e55151876a65ef695dc8aa82a62327.
It would be helpful to have these merged to main.

**Comment by xserra** [comment]
fixed
