### ISSUE TITLE
Compilation issues on linux/ubuntu (12.04 LTS)

### ISSUE THREAD

**Issue by dhruvkapur91** [MTG/sms-tools#16]
So I set up a virtual machine with the above linux and install all the dependencies mentioned (seems to have installed fine - can import all of them in an interactive session)

I run 

`$ python compileModule.py build_ext --inplace`
I get:
running build_ext
skipping 'cutilFunctions.c' Cython extension (up-to-date)

Then when I do
`$ python models_GUI.py `
I get the following warning and nothing happens:
-------------------------------------------------------------------------------
Warning:
Cython modules for some of the core functions were not imported.
Please refer to the README file for the instructions to compile the cython modules
Exiting the code!!
-----------------------

Any help is appreciated. Thanks.

**Comment by AveRapina** [comment]
Any Update on This?
Thanks in advance

**Comment by xserra** [comment]
These are issues of installation of python modules, in this case of Cython, in the forum of the ASPMA course are discussed: https://class.coursera.org/audio-002/forum/

please ask this type of questions there.

**Comment by dale451** [comment]
I don't know why I am receiving these emails. Could somebody please remove me from the list?

Warm regards,


Dale Garland
(sent from my iPhone)

On 21 Sep 2015, at 18:13, Xavier Serra <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #16<https://github.com/MTG/sms-tools/issues/16>.

-

**Comment by xserra** [comment]
You have to un-follow this repository (click the Unwatch button)

**Comment by alataffective** [comment]
I am having the same problem as described by @mr-nano (on macOS). Unfortunately, the forum link above does not work for me. @xserra or @HSOFEUP, are you able to help please?
