### ISSUE TITLE
Issue launching models_GUI.py on raspberry pi

### ISSUE THREAD

**Issue by loicreboursiere** [MTG/sms-tools#18]
Hi,

I'm using my raspberry pi with the raspbian os to run those examples. All the installations went fine.
But I've got the following error when launching models_GUI.py :
Traceback (most recent call last):
  File "models_GUI.py", line 14, in <module>
    root = Tk( ) 
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1712, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable

python-tk is installed with its last version.

Any help more than welcome :) 

Thanks

**Comment by claypipkin** [comment]
Did you ever get this working?

**Comment by loicreboursiere** [comment]
Wow, it was quite a while, but I think it was a silly beginner mistake. 
I didn't lauch any GUI at all, I was only using the command line mode on which is the raspberry when you start it. When you lauch the global raspbian GUI (startx) everything works fine !

Hope that helps
