### ISSUE TITLE
SMS Tools 

### ISSUE THREAD

**Issue by Samizdat630** [MTG/sms-tools#24]
Hey guys,

I'm just now starting the course, and I finally was able to run Ubuntu through Virtual Box. But the instructions on the websites have me confused. I entered:

 $ sudo apt-get install python-dev ipython python-numpy python-matplotlib python-scipy python-pygame cython

(note, for some reason I was not able to even copy or paste that line of code into the module). 

Am I doing something wrong? The SMS Tools Master folder is already downloaded. 

Best, 
Carl

**Comment by sankalpg** [comment]
Hi Carl,

I couldn't completely understand the issue you are facing. After you execute the line you mentioned in the terminal do you get errors? what exactly is the issue can you include.

**Comment by Samizdat630** [comment]
I receive the following mention in by Ubuntu terminal: 
![screen shot ubuntu](https://cloud.githubusercontent.com/assets/6644087/5891583/348d5658-a464-11e4-8043-a627eeed9c56.png)

**Comment by sankalpg** [comment]
Are you sure you are executing the commands in Ubuntu Shell? it doesn;t look like..

**Comment by Samizdat630** [comment]
What would the proper command be?

**Comment by rgonnering** [comment]
Open a terminal

at the prompt, enter

sudo apt-get install python-dev ipython python-numpy python-matplotlib
python-scipy python-pygame cython

**Comment by Samizdat630** [comment]
Opened up Ubuntu through Virtual Box. Opened the terminal (still unable to copy and paste). I also tried using Python through Canopy as well. Still says invalid syntax. Maybe I downloaded the wrong version of Ubuntu?
![ubuntu desktop version run through virtual box](https://cloud.githubusercontent.com/assets/6644087/5894137/c6bfb3be-a4c2-11e4-9f26-6a4aa65b0970.png)
![screen shot 2015-01-25 at 6 46 47 pm](https://cloud.githubusercontent.com/assets/6644087/5894138/ca98dae2-a4c2-11e4-82a1-7be81b52e225.png)

**Comment by rgonnering** [comment]
You are entering it into python.

You need to enter it into Linux. Goto 'Terminal Emulator' in the Ubuntu
menu.

**Comment by Samizdat630** [comment]
The first screen cap is the terminal emulator, no? I accessed it by double clicking the only option of the far left here:
![screen shot 2015-01-25 at 7 21 12 pm](https://cloud.githubusercontent.com/assets/6644087/5894285/7e8d734c-a4c7-11e4-897e-6af280188b73.png)

**Comment by rgonnering** [comment]
The terminal editor looks like this:

[image: Inline image 1]

Have you loaded Ubuntu into VirtualBox?

**Comment by Samizdat630** [comment]
I'm reinstalling everything, starting from square one again. The Desktop version of Ubuntu is the correct version, right?

**Comment by rgonnering** [comment]
I used the Desktop version of Ubuntu 14.04.

**Comment by GarrettArm** [comment]
This issue could be closed.  The author was entering bash commands into a bios shell, and also into the python interactive prompt.  He needs to enter the commands into a bash shell (E.g., Terminal).

**Comment by xserra** [comment]
OK, done.

**Comment by gmcuello** [comment]
Hi I've started the course, downloaded the Virtual Box image but I don't know the Student password tin order to access ubuntu. Can you tellme where are the setup instructions?
Thanks in advance

**Comment by gmcuello** [comment]
Thanks Eduardo it worked!
