### ISSUE TITLE
Floating point rounding off bug

### ISSUE THREAD

**Issue by lfmunoz** [MTG/sms-tools#25]
software/models/dftModel.py

line 37:
pX = np.unwrap(np.angle(X[:hN])) # unwrapped phase spectrum of positive frequencies

This is a bug because the fft function might return really small values (close to 0) that can be either positive or negative. For example you might get

-0.000000000007 + -.000000000001 j
or
-0.000000000007 + .000000000001 j
or
0.000000000007 + .000000000001 j

but really this is meant to be
0+0j 

Those negative or positive signs makes a big difference for what the angle is.

**Comment by xserra** [comment]
Thanks, I added a threshold to fix this, so any number below it is assigned to 0. I do not know what would be a good one, now it is 1e-5
