### ISSUE TITLE
Copyright issues, users constantly ignore copyright

### ISSUE THREAD

**Issue by qubodup** [MTG/sms-tools#30]
Hello, I'm a volunteer moderator at freesound.org

A lot of users are uploading their sounds to freesound using the sounds in this package as sources.

Most provide info about the sounds being related to the course and some link to this repository or the collection on freesound but rarely people attribute the original copyright holders, which is required by ccby and ccbync licenses.

In this repository, no attribution is given to the copyright holders of the sounds.This ignores the requirement for attribution.

In the readme it is stated that the sounds are cc-by-sa-nc licensed, which one may not do, if they only redistribute (rather than remix) a cc-by or cc-by-nc licensed sound ( https://creativecommons.org/licenses/by/3.0/legalcode 4.a "You may not sublicense the Work." )

If the sounds really were cc-by-sa-nc, remixes could also not be uploaded to freesound, as such a license is incompatible to the ones available there (probably due to its impracticability).

As a result I keep writing the following message to them.

<blockquote>Hello,

Your course material doesn't explain the importance of copyright when using 3rd party works.

The sounds you use most likely require attribution. Some might prohibit commercial use.

When you upload sounds to freesound, you pick one of 3 licenses, one of which prohibits commercial use and requires attribution, one only requires attribution and one requires nothing.

You need to check what the original sound requires and possibly change the license of you upload accordingly. Double-check the changes.

If the original sound requires attribution, you need to put a link in the description of your upload to the original.

Find the link to the sound you used in
http://freesound.org/home/attribution/ and put it in your description. Do not just link to a user or collection.

Double-check after editing.

Thanks!
</blockquote>

All this wastes time of moderators and of course participants.

Please
1. follow the license attribution requirements to set a good example to your course participants
2. make an effort to teach course participants that they have to give attribution to the original sound copyright holders if the license requires it.

alternatively you could switch to using cc0 sounds only.

**Comment by ajaysmurthy** [comment]
@qubodup: Hi! I am a TA for the course. Thanks for bringing this to our notice. We will update the README with proper attribution and teach the course participants about CC licenses and using them in Freesound.

**Comment by xserra** [comment]
This was done, closing this one.
