### ISSUE TITLE
How to modulate one waveform/track with another to achieve FM(Freq. Modulation)?

### ISSUE THREAD

**Issue by MichaelZP** [MTG/sms-tools#35]
How to modulate one waveform/track with another to achieve FM(Freq. Modulation)?
![fm_](https://cloud.githubusercontent.com/assets/17249917/16711983/a1aafe96-4677-11e6-93dd-da7a99dad9f3.jpg)

**Comment by xserra** [comment]
This is not really part of sms-tools, closing.
