### ISSUE TITLE
exception for "$python models_GUI.py" step

### ISSUE THREAD

**Issue by loopbum** [MTG/sms-tools#40]
Mac OS X 10.11.6 El Capitan, XCode 8 installed.

$ python models_GUI.py

2016-09-30 16:32:15.073 python[8744:452491] -[NSApplication _setup:]: unrecognized selector sent to instance 0x107ac9430

2016-09-30 16:32:15.075 python[8744:452491] An uncaught exception was raised

2016-09-30 16:32:15.075 python[8744:452491] -[NSApplication _setup:]: unrecognized selector sent to instance 0x107ac9430

2016-09-30 16:32:15.075 python[8744:452491] (

0   CoreFoundation                      0x00007fff908564f2 __exceptionPreprocess + 178

1   libobjc.A.dylib                     0x00007fff8bd7973c objc_exception_throw + 48

2   CoreFoundation                      0x00007fff908c01ad -[NSObject(NSObject) doesNotRecognizeSelector:] + 205

3   CoreFoundation                      0x00007fff907c6571 **_forwarding**_ + 1009

4   CoreFoundation                      0x00007fff907c60f8 _CF_forwarding_prep_0 + 120

5   Tk                                  0x0000000101a52948 TkpInit + 476

6   Tk                                  0x00000001019cda6e Tk_Init + 1799

7   _tkinter.so                         0x00000001002e6a26 Tcl_AppInit + 86

8   _tkinter.so                         0x00000001002e43f1 Tkinter_Create + 1185

9   libpython2.7.dylib                  0x00000001000a3302 PyEval_EvalFrameEx + 3730

10  libpython2.7.dylib                  0x00000001000ac7dc PyEval_EvalCodeEx + 2092

11  libpython2.7.dylib                  0x0000000100035c1b function_call + 347

12  libpython2.7.dylib                  0x000000010000c761 PyObject_Call + 97

13  libpython2.7.dylib                  0x000000010001e7d7 instancemethod_call + 503

14  libpython2.7.dylib                  0x000000010000c761 PyObject_Call + 97

15  libpython2.7.dylib                  0x00000001000a1874 PyEval_CallObjectWithKeywords + 180

16  libpython2.7.dylib                  0x000000010001a771 PyInstance_New + 273

17  libpython2.7.dylib                  0x000000010000c761 PyObject_Call + 97

18  libpython2.7.dylib                  0x00000001000a35a5 PyEval_EvalFrameEx + 4405

19  libpython2.7.dylib                  0x00000001000ac7dc PyEval_EvalCodeEx + 2092

20  libpython2.7.dylib                  0x00000001000ac856 PyEval_EvalCode + 54

21  libpython2.7.dylib                  0x00000001000cb3d4 PyRun_FileExFlags + 164

22  libpython2.7.dylib                  0x00000001000cc709 PyRun_SimpleFileExFlags + 409

23  libpython2.7.dylib                  0x00000001000e01ca Py_Main + 2938

24  python                              0x0000000100000f14 start + 52

)

2016-09-30 16:32:15.076 python[8744:452491] **\* Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSApplication _setup:]: unrecognized selector sent to instance 0x107ac9430'

**\* First throw call stack:

(

0   CoreFoundation                      0x00007fff908564f2 __exceptionPreprocess + 178

1   libobjc.A.dylib                     0x00007fff8bd7973c objc_exception_throw + 48

2   CoreFoundation                      0x00007fff908c01ad -[NSObject(NSObject) doesNotRecognizeSelector:] + 205

3   CoreFoundation                      0x00007fff907c6571 **_forwarding**_ + 1009

4   CoreFoundation                      0x00007fff907c60f8 _CF_forwarding_prep_0 + 120

5   Tk                                  0x0000000101a52948 TkpInit + 476

6   Tk                                  0x00000001019cda6e Tk_Init + 1799

7   _tkinter.so                         0x00000001002e6a26 Tcl_AppInit + 86

8   _tkinter.so                         0x00000001002e43f1 Tkinter_Create + 1185

9   libpython2.7.dylib                  0x00000001000a3302 PyEval_EvalFrameEx + 3730

10  libpython2.7.dylib                  0x00000001000ac7dc PyEval_EvalCodeEx + 2092

11  libpython2.7.dylib                  0x0000000100035c1b function_call + 347

12  libpython2.7.dylib                  0x000000010000c761 PyObject_Call + 97

13  libpython2.7.dylib                  0x000000010001e7d7 instancemethod_call + 503

14  libpython2.7.dylib                  0x000000010000c761 PyObject_Call + 97

15  libpython2.7.dylib                  0x00000001000a1874 PyEval_CallObjectWithKeywords + 180

16  libpython2.7.dylib                  0x000000010001a771 PyInstance_New + 273

17  libpython2.7.dylib                  0x000000010000c761 PyObject_Call + 97

18  libpython2.7.dylib                  0x00000001000a35a5 PyEval_EvalFrameEx + 4405

19  libpython2.7.dylib                  0x00000001000ac7dc PyEval_EvalCodeEx + 2092

20  libpython2.7.dylib                  0x00000001000ac856 PyEval_EvalCode + 54

21  libpython2.7.dylib                  0x00000001000cb3d4 PyRun_FileExFlags + 164

22  libpython2.7.dylib                  0x00000001000cc709 PyRun_SimpleFileExFlags + 409

23  libpython2.7.dylib                  0x00000001000e01ca Py_Main + 2938

24  python                              0x0000000100000f14 start + 52

)

libc++abi.dylib: terminating with uncaught exception of type NSException

Abort trap: 6

$

**Comment by tardate** [comment]
@loopbum see #36 - same problem, and fix worked for me
