### ISSUE TITLE
when i press Compute the models_GUI crashes saying windows from Qt needed

### ISSUE THREAD

**Issue by koinas** [MTG/sms-tools#41]
Running python models_GUI.py the program starts but when i select Computer is crashes saying:
This application failed to start because it could not find or load the Qt platfo
rm plugin "windows"
in "".

Is this program really built with QT?

**Comment by koinas** [comment]
I have installed the PyQT and now after pressing Compute the plot window appear. But "python.exe stopped working" message appear and application crashes.

**Comment by mrtcnkrcby** [comment]
My python quitted unexpectedly when I clicked models_GUI's compute button in Mac OSX where python 2.7 was installed. So I installed Ubuntu on VirtualBox and followed the instructions in Readme. It works now.
