### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by Twangist** [MTG/sms-tools#42]
please?
It _is_ 2016, after all.

**Comment by bzamecnik** [comment]
Already done more than a year ago: https://github.com/bzamecnik/sms-tools / https://pypi.python.org/pypi/smst It's a fork and probably not going to be merged back due to totally rewritten API, so that the videos have to be recorded again. :(

**Comment by xserra** [comment]
We will port sms-tools to python 3 and redo the videos this summer.
