### ISSUE TITLE
Hardcoded value in sprModelAnal function?

### ISSUE THREAD

**Issue by thisisjl** [MTG/sms-tools#44]
Hi, I am not sure if it is a bug, but in the [line 25 of the sprModel file,](https://github.com/MTG/sms-tools/blob/master/software/models/sprModel.py#L25) there is a hardcoded value for Ns. Is that on purpose?
I was playing with different values of N and H and I got errors because of that.

Thanks a lot for this very useful library!

**Comment by xserra** [comment]
Yes, this is done on purpose. It is used for synthesis and there is no much need to change it. It does not affect the analysis.
