### ISSUE TITLE
SSL Handshake issue on submit

### ISSUE THREAD

**Issue by waprin** [MTG/sms-tools#48]
OS X Homebrew Python 2.7 , get the following issue when running `python submitA2.py`.

```
requests.exceptions.SSLError: [Errno 1] _ssl.c:504: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure
```

Maybe an issue on my end or maybe a bad certificate?

**Comment by xserra** [comment]
This is not an sms-tools problem, closing.
