### ISSUE TITLE
Complie C - OS X ImportError: No module named Cython.Distutils

### ISSUE THREAD

**Issue by ralphonz** [MTG/sms-tools#59]
When trying to run  `python compileModule.py build_ext --inplace` I'm getting the error:

`File "compileModule.py", line 4, in <module>
    from Cython.Distutils import build_ext
ImportError: No module named Cython.Distutils`

Can anyone help to solve this?

I'm on Mac OS X - Cython installed via pip:
`pip install Cython
Requirement already satisfied: Cython in /usr/local/lib/python2.7/site-packages`

But no modules are found...

**Comment by EMCP** [comment]
retry with `python3 compuleModule.py....` .. worked for me, not sure why they recommend 2.x
