### ISSUE TITLE
Timbre preserve

### ISSUE THREAD

**Issue by sankalpg** [MTG/sms-tools#6]
Hi Xavier,

In pitch shift while preserving timbre, the new frequency values outside the old spectrum (range) do not get 0 mag, instead below F0 and above the highest harmonic the spectrum is made constant. This is the way its done in old matlab code. Do we want to do it the same way?

Also there is probably a bug in old matlab code. Instead of Ns in the interp function it should be hNs.

**Comment by xserra** [comment]
closing.
