### ISSUE TITLE
Problem running models_GUI.py

### ISSUE THREAD

**Issue by eagomez2** [MTG/sms-tools#62]
I already compiled the Cython files but I can't run models_GUI.py

I'm using OS X 10.12.5 and Python 2.7.13 through terminal. I want to avoid [installing Anaconda as another user suggested](http://flothesof.github.io/sms-tools-MacOSX-Anaconda.html) if possible. Any help is appreciated, thanks!

```
> MacBook-Pro-de-Esteban:models_interface eagomez$ python models_GUI.py
>   File "models_GUI.py", line 9
>     except ImportError
>                      ^
> SyntaxError: invalid syntax
> MacBook-Pro-de-Esteban:models_interface eagomez$ 
```

**Comment by EMCP** [comment]
I've been sticking to python3, so for the GUI i had to install tkinter via

`sudo apt-get install python3-tk` 

you might want to try getting Tkinter installed on OSX

**Comment by Marcio547** [comment]
I've tried to Compute the STFT using the models_gui.py file, but as I click on "Compute", a new window opens with screenshot from my actual screen and then it freezes. I've already tried to rollback to earlier version of numpy (as suggested on #49) and also tried to do the rollback of numpy, but nothing has worked. Does anybody have any idea of what could be happening?

**Comment by EMCP** [comment]
@Marcio547 I would uninstall all the `apt-get` installed python packages and just use `pip install` ... their instructions are not common practice anymore now that pip is much more up to date

**Comment by Marcio547** [comment]
Well I tried again using python 2.7 and it has worked.... just run on terminal
python2 models_GUI.py and it went everything ok

**Comment by jjsauma** [comment]
When running in MacOS 10.12.6 it shows this error:

sms-tools-master/software/models_interface$ python models_GUI.py
Traceback (most recent call last):
  File "models_GUI.py", line 22, in <module>
    from dftModel_GUI_frame import *
  File "/Users/joaquinjimenez/Google Drive/UPF SMC/Procesamiento Digital de Señales/sms-tools-master/software/models_interface/dftModel_GUI_frame.py", line 14, in <module>
    import dftModel_function
  File "/Users/joaquinjimenez/Google Drive/UPF SMC/Procesamiento Digital de Señales/sms-tools-master/software/models_interface/dftModel_function.py", line 4, in <module>
    import matplotlib.pyplot as plt
  File "/Users/joaquinjimenez/anaconda2/lib/python2.7/site-packages/matplotlib/pyplot.py", line 69, in <module>
    from matplotlib.backends import pylab_setup
  File "/Users/joaquinjimenez/anaconda2/lib/python2.7/site-packages/matplotlib/backends/__init__.py", line 14, in <module>
    line for line in traceback.format_stack()
  File "/Users/joaquinjimenez/anaconda2/lib/python2.7/site-packages/matplotlib/backends/__init__.py", line 16, in <genexpr>
    if not line.startswith('  File "<frozen importlib._bootstrap'))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xcc in position 79: ordinal not in range(128)

**Comment by EMCP** [comment]
@jjsauma , you have an `ñ` in the path, did you try moving the project out of that path and retrying?'

or might be this https://stackoverflow.com/questions/21129020/how-to-fix-unicodedecodeerror-ascii-codec-cant-decode-byte

**Comment by jjsauma** [comment]
Thank you! How Could I have missed that? I feel silly.

**Comment by EMCP** [comment]
ñ too spicy for Python jaja
