### ISSUE TITLE
Convert assignments to Python Notebook?

### ISSUE THREAD

**Issue by EMCP** [MTG/sms-tools#66]
Would the course proctors and repo owner be open if I created a PR with the assignments converted into a python notebook?  Seems it would be a good idea for the plotting components later in the class, bring everything into the modern workflow so to speak..

thoughts?

**Comment by xserra** [comment]
This would be great!!! We have been planning on doing it ourselves, but if you can do it that would be wonderful.

**Comment by EMCP** [comment]
Great!

Where would you want them if I wrote them ?  perhaps next to the originals or in their own new folder?  I could PR it and leave a review request to you and the team

**Comment by xserra** [comment]
Let's do a new folder. In the process, I would like to change a few things of the assignments.

**Comment by EMCP** [comment]
I PR'd the first 3 weeks just to make sure it's meeting expectations, if it looks okay I can finish weeks 4 through 10 in the same style.

If not let me know how you may want it changed.

https://github.com/MTG/sms-tools/pull/67

**Comment by xserra** [comment]
Sorry I did not look at it until now. They look very good, so I accepted the pull request. So feel free to do the rest.
