### ISSUE TITLE
GUI crashing on Ubuntu 16 LTS (Miniconda, python 2/3) - FIX

### ISSUE THREAD

**Issue by kaczorrrro** [MTG/sms-tools#68]
Not sure if anyone else has this problem, but none of the windows with plots would render at all. Simple solution was to put 
```
import matplotlib
matplotlib.use('TkAgg')
```
out of if statement (it didn't execute, but seems it should have)

so my final models_GUI.py looks like

```
import sys
if sys.platform == 'darwin':
    print("True")
import matplotlib
matplotlib.use('TkAgg')

try:
#rest of code
```

Now it works with both python 2 and 3

**Comment by xserra** [comment]
Thanks, I made this change.
