### ISSUE TITLE
Misleading Error Message within the submit.py  "file output data type of your function doesn't match..."

### ISSUE THREAD

**Issue by zipzit** [MTG/sms-tools#72]
This error message "Type error in Part ... - The output data type of your function doesn't match the expected data type: (<type 'numpy.ndarray'>)" is very misleading.

That error message is generated when ever a response doesn't match the expected data type.  But what happens when there is NO RESPONSE ?  That error message doesn't help the user in the least.  

Based on the testing actually performed within submitA2.py, the error message should probably say **"Error in Part x.. Either the return response from your function call is missing (e.g. None), or the output data type of your function doesn't match the expected data type..."**

Actually its probably better to just add another test for the presence of an answer, with an accurate error message, before testing for return type.  (proposed error message:  **Oops.. no data received from your function call  !** ) 

use testing?  what if the user forgot to `return x`  or in my case I did all of my original work in a copied file A2Part1_my_initials.py .  It's not a surprise that the submit wasn't finding anything.

**Comment by xserra** [comment]
this is not a problem of this repository, this relates to the code in the Coursera course.
