### ISSUE TITLE
Lobe crossing Nyquist bin bug?

### ISSUE THREAD

**Issue by agligovic** [MTG/sms-tools#73]
https://github.com/MTG/sms-tools/blob/ca5e34ee0e786423f6f6efae15dababc4dd6d564/software/models/utilFunctions.py#L190
Is there a possible bug when lobe has crossed the Nyquist bin?
Shouldn't this be 
`Y[N - b[m]] += lmag[m]*np.exp(-1j*ipphase[i]) `
?

I am trying to figure out sinusoid synthesis, my apologies if I have misunderstood something and raised a false alarm.

Br.
A.G.

**Comment by xserra** [comment]
when the lobe crosses 0 or the Nyquist bin there is aliasing, so the lobe goes to the negative frequencies, at it should be.
