### ISSUE TITLE
matplotlib figure issue on 1280 x 800 screen. No interactive controls.

### ISSUE THREAD

**Issue by audionuma** [MTG/sms-tools#76]
Hello,
I'm having an issue running sms-tools on a 1280 x 800 screen.
System : Ubuntu 18.04 running as a guest on VirtualBox on a MacBook Pro 13" host.
Native screen size : 1280 x 800, guest screen size : 1280 x 800.
Can be reproduced under Mac OS 10.10.5 native or Debian Stretch as a VirtualBox guest.

**Steps to reproduce :**
```
$ python --version
Python 2.7.15rc1
$ cd /sms-tools/software/models_interface/
$ python models_GUI.py
```
The tk window shows up as expected.
Click on the 'compute' button.
A matplotlib figure opens up full screen.
No interactive controls (zoom, etc.) are available on the matplotlib window.

**Working around**
Edit the `dftModel_function.py` file.
Replace the line 39 :
`plt.figure(figsize=(12, 9))`
by
`plt.figure(figsize=(9, 6))`

`$ python models_GUY.py`
The tk windows shows up as expected.
Click on the `compute` button.
A matplotlib figure opens up not full screen.
Interactive controls are available.

**Comment by xserra** [comment]
Thanks, I fixed this.
