### ISSUE TITLE
module 'utilFunctions_C' has no attribute 'twm'

### ISSUE THREAD

**Issue by jiemojiemo** [MTG/sms-tools#79]
I got a error when I try to conpute the HPS 

![default](https://user-images.githubusercontent.com/13779459/47636938-0973e380-db95-11e8-80b6-db93e3ba6c9a.png)

**Comment by lectricas** [comment]
@jiemojiemo  how do you solve this?

**Comment by jiemojiemo** [comment]
> @jiemojiemo how did you solve this?
run code on Linux

**Comment by Ogala** [comment]
This error still persists on Mac

**Comment by danitm77** [comment]
Actually I'm running on Linux and I get same error msg

**Comment by danitm77** [comment]
I just saw that you need to install properly the package according to the README file. Probably this step fixes the issue:

> for using the tools, after downloading the whole package, you need to compile some C functions. For that you should go to the directory software/models/utilFunctions_C and type:
> 
> $ python compileModule.py build_ext --inplace

**Comment by Provatiscus** [comment]
> I just saw that you need to install properly the package according to the README file. Probably this step fixes the issue:
> 
> > for using the tools, after downloading the whole package, you need to compile some C functions. For that you should go to the directory software/models/utilFunctions_C and type:
> > $ python compileModule.py build_ext --inplace

THANKS !

**Comment by abeyna** [comment]
> 

I got an error: Could not create 'build': Permission denied after trying to compile it. Did you see this before?

**Comment by abeyna** [comment]
> I just saw that you need to install properly the package according to the README file. Probably this step fixes the issue:
> 
> > for using the tools, after downloading the whole package, you need to compile some C functions. For that you should go to the directory software/models/utilFunctions_C and type:
> > $ python compileModule.py build_ext --inplace

I got an error: Could not create 'build': Permission denied after trying to compile it. Did you see this before?

**Comment by ajiva84** [comment]
I got this error when I tried to compile in windows: 

tools\software\models\utilFunctions_C\compileModule.py", line 4, in <module>
    from Cython.Distutils import build_ext
ModuleNotFoundError: No module named 'Cython'
