### ISSUE TITLE
Cannot compile C functions

### ISSUE THREAD

**Issue by jiemojiemo** [MTG/sms-tools#80]
when I run

`python compileModule.py build_ext --inplace`

I got error
```
running build_ext
skipping 'cutilFunctions.c' Cython extension (up-to-date)
building 'utilFunctions_C' extension
error: Unable to find vcvarsall.bat
```

python=3.6
windows 10

**Comment by dnsglk** [comment]
@jiemojiemo Maybe this will help
https://blogs.msdn.microsoft.com/pythonengineering/2016/04/11/unable-to-find-vcvarsall-bat/

Anyway, as the manual tells, Ubuntu is strongly preferred over other OS.

**Comment by geertdijkstra** [comment]
I managed to compile the c files by using the virtual Linux environment on Windows called MSYS2: [https://www.msys2.org/]

perhaps you can give this a try and use google to figure out how to set everything up properly ;)

**Comment by dijkstrah** [comment]
> Anyway, as the manual tells, Ubuntu is strongly preferred over other OS.

I respectfully disagree, I prefer Windows over Ubuntu. It is just a matter of setting up your environment properly. Clearly if you have never worked with C or C++ in a  native windows environment, you will run into trouble and you will not know what to do.

I have the sms tools running on Python 3.7.4 64 bit, built with Visual Studio 2019, Windows SDK 10.0.17763.0. 

For this code to compile on Windows (10), you need an install of Visual Studio and a Windows SDK. If you startup a command line environment through vcvarsall.bat you will find the build starts working much better, up until the moment it bails with a message on how it fails to find m.lib for linking. 

This is remediated by removing the libraries=['m'] part from the compileModule.py script (in the setup block). Windows does not need a seperate m.lib so this is superfluous.

**Comment by avishaik** [comment]
For anyone still struggling with the build issue with the error:
`error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
`
What worked for me was to install the Windows SDK and Microsoft visual studio and choosing python development.

See the following for more information:
https://devguide.python.org/getting-started/setup-building/index.html#windows
https://wiki.python.org/moin/WindowsCompilers#Compilers_Installation_and_configuration
