### ISSUE TITLE
Different Spectrum Plot

### ISSUE THREAD

**Issue by Marcio547** [MTG/sms-tools#83]
Hi,

I am in the beginning of the "Audio Signal Processing for Musical Applications" course and I was following the instructions about running the SMS-tools.
During the video, I noticed that the spectrogram out when I tried to use the STFT in the example was looking different. I am not sure if it is only the color map plotted, or if something has gone wrong.

This is my output:
![grafik](https://user-images.githubusercontent.com/18644423/49698627-796e8400-fbad-11e8-87fa-b54ba5f5f5c9.png)

And this is the output from the video from the course:

![grafik](https://user-images.githubusercontent.com/18644423/49698635-a458d800-fbad-11e8-9c2f-28ae21bcfb1a.png)

Is there something wrong? Or is just the color map?

**Comment by vitorsr** [comment]
It's just the colormap. Try jet 😊
