### ISSUE TITLE
utilFunctions: genBhLobe consts values

### ISSUE THREAD

**Issue by shuguang101** [MTG/sms-tools#87]
line 150: consts = [0.35875, 0.48829, 0.14128, 0.01168]. I am a beginner. I don't understand why consts != [0.35875, -0.48829, 0.14128, -0.01168] (according to Fourier linearity properties）Did I misunderstand something?

**Comment by xserra** [comment]
We are computing the magnitude spectrum of the window, thus we use the absolute value.
