### ISSUE TITLE
Interger factors in wavread should not have 1 subtracted from them.

### ISSUE THREAD

**Issue by kaushalsali** [MTG/sms-tools#88]
In utilFunctions.py, subtracting 1 from integer factors may result in values lower than -1 if a sample was quantized to the last negative step.
```
INT16_FAC = (2**15)-1
INT32_FAC = (2**31)-1
INT64_FAC = (2**63)-1
```
 eg. For `dtype=int16` the range of values is `[-32678, 32767]`. If a sample has value of `-32678` then dividing by `INT16_FAC=(2**15)-1` will give `-1.0000305185`.
The factors should be: 
```
INT16_FAC = (2**15)
INT32_FAC = (2**31)
INT64_FAC = (2**63)
```

**Comment by xserra** [comment]
solved
