### ISSUE TITLE
cannot compile C functions Mac

### ISSUE THREAD

**Issue by zzgsdddz** [MTG/sms-tools#89]
when I tried :
`python compileModule.py build_ext --inplace`

it showed:
`Traceback (most recent call last):
  File "compileModule.py", line 4, in <module>
    from Cython.Distutils import build_ext
ImportError: No module named Cython.Distutils`

so I redid:
`pip install Cython`
it succeeded

however, the error still shows.
Does anyone know how to resolve this?

**Comment by Gnai** [comment]
did you get any solution for this ?!

**Comment by Gnai** [comment]
actually try python3 for this or even for the file you are trying to execute

**Comment by martinfoakes** [comment]
> actually try python3 for this or even for the file you are trying to execute

Was having the same issue and that fixed it all for me thanks

**Comment by Gnai** [comment]
Your welcome :)
