### ISSUE TITLE
Broken GUI on mac

### ISSUE THREAD

**Issue by joanne254** [MTG/sms-tools#95]
Hi. Installed dependencies via `pipenv` as required, launched the `models_GUI.py` script without errors, but the interface is pretty broken (missing and hidden labels, incomplete menus) and the plots don't show up. There's no error though.
OS: MasOS Mojave, version 10.14.6
Python: Python 3.8.1

Here are some screenshots. Any suggestions?

<img width="683" alt="Screenshot 2020-02-15 at 21 13 08" src="https://user-images.githubusercontent.com/1435192/74594775-3b36e500-503a-11ea-9aac-9c1e9b07de99.png">
<img width="683" alt="Screenshot 2020-02-15 at 21 13 16" src="https://user-images.githubusercontent.com/1435192/74594779-425df300-503a-11ea-8724-cd916a4252cb.png">
<img width="1287" alt="Screenshot 2020-02-15 at 21 13 52" src="https://user-images.githubusercontent.com/1435192/74594780-4558e380-503a-11ea-8052-e668de2985b4.png">

**Comment by dpunosevac** [comment]
I can confirm this issue. It also happens on my Mac.

Details:
OS: MacOS Catalina, Version 10.15.3
Python: 3.7.3

**Comment by miguelfrde** [comment]
I was able to repro this issue also on Catalina on **dark mode**. As a quick workaround switching to **light mode** fixes it. [This stackoverflow post][post] has more context.

[post]: https://stackoverflow.com/questions/52529403/button-text-of-tkinter-does-not-work-in-mojave
